package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TExpert generated by hbm2java
 */
@Entity
@Table(name = "t_expert", catalog = "db_expert_robot")
public class TExpert implements java.io.Serializable {

	private Integer expertId;
	private String name;
	private String gender;
	private String email;
	private String address;
	private String homepage;
	private int paperNum;
	private int patentNum;
	private int paperReferedNum;
	private String prize;
	private String experience;
	private String info;
	private String achievement;
	private String activity;
	private Set<TRelExpertPatent> TRelExpertPatents = new HashSet<TRelExpertPatent>(
			0);
	private Set<TRelExpertTopic> TRelExpertTopics = new HashSet<TRelExpertTopic>(
			0);
	private Set<TRelExpertField> TRelExpertFields = new HashSet<TRelExpertField>(
			0);
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TRelExpertOrg> TRelExpertOrgs = new HashSet<TRelExpertOrg>(0);
	private Set<TRelExpertPaper> TRelExpertPapers = new HashSet<TRelExpertPaper>(
			0);

	public TExpert() {
	}

	public TExpert(String name, String gender, int paperNum, int patentNum,
			int paperReferedNum) {
		this.name = name;
		this.gender = gender;
		this.paperNum = paperNum;
		this.patentNum = patentNum;
		this.paperReferedNum = paperReferedNum;
	}

	public TExpert(String name, String gender, String email, String address,
			String homepage, int paperNum, int patentNum, int paperReferedNum,
			String prize, String experience, String info, String achievement,
			String activity, Set<TRelExpertPatent> TRelExpertPatents,
			Set<TRelExpertTopic> TRelExpertTopics,
			Set<TRelExpertField> TRelExpertFields, Set<TUser> TUsers,
			Set<TRelExpertOrg> TRelExpertOrgs,
			Set<TRelExpertPaper> TRelExpertPapers) {
		this.name = name;
		this.gender = gender;
		this.email = email;
		this.address = address;
		this.homepage = homepage;
		this.paperNum = paperNum;
		this.patentNum = patentNum;
		this.paperReferedNum = paperReferedNum;
		this.prize = prize;
		this.experience = experience;
		this.info = info;
		this.achievement = achievement;
		this.activity = activity;
		this.TRelExpertPatents = TRelExpertPatents;
		this.TRelExpertTopics = TRelExpertTopics;
		this.TRelExpertFields = TRelExpertFields;
		this.TUsers = TUsers;
		this.TRelExpertOrgs = TRelExpertOrgs;
		this.TRelExpertPapers = TRelExpertPapers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "expertId", unique = true, nullable = false)
	public Integer getExpertId() {
		return this.expertId;
	}

	public void setExpertId(Integer expertId) {
		this.expertId = expertId;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "gender", nullable = false, length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "address", length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "homepage", length = 50)
	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	@Column(name = "paperNum", nullable = false)
	public int getPaperNum() {
		return this.paperNum;
	}

	public void setPaperNum(int paperNum) {
		this.paperNum = paperNum;
	}

	@Column(name = "patentNum", nullable = false)
	public int getPatentNum() {
		return this.patentNum;
	}

	public void setPatentNum(int patentNum) {
		this.patentNum = patentNum;
	}

	@Column(name = "paperReferedNum", nullable = false)
	public int getPaperReferedNum() {
		return this.paperReferedNum;
	}

	public void setPaperReferedNum(int paperReferedNum) {
		this.paperReferedNum = paperReferedNum;
	}

	@Column(name = "prize", length = 65535)
	public String getPrize() {
		return this.prize;
	}

	public void setPrize(String prize) {
		this.prize = prize;
	}

	@Column(name = "experience", length = 65535)
	public String getExperience() {
		return this.experience;
	}

	public void setExperience(String experience) {
		this.experience = experience;
	}

	@Column(name = "info", length = 65535)
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	@Column(name = "achievement", length = 65535)
	public String getAchievement() {
		return this.achievement;
	}

	public void setAchievement(String achievement) {
		this.achievement = achievement;
	}

	@Column(name = "activity", length = 65535)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TExpert")
	public Set<TRelExpertPatent> getTRelExpertPatents() {
		return this.TRelExpertPatents;
	}

	public void setTRelExpertPatents(Set<TRelExpertPatent> TRelExpertPatents) {
		this.TRelExpertPatents = TRelExpertPatents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TExpert")
	public Set<TRelExpertTopic> getTRelExpertTopics() {
		return this.TRelExpertTopics;
	}

	public void setTRelExpertTopics(Set<TRelExpertTopic> TRelExpertTopics) {
		this.TRelExpertTopics = TRelExpertTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TExpert")
	public Set<TRelExpertField> getTRelExpertFields() {
		return this.TRelExpertFields;
	}

	public void setTRelExpertFields(Set<TRelExpertField> TRelExpertFields) {
		this.TRelExpertFields = TRelExpertFields;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TExperts")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TExpert")
	public Set<TRelExpertOrg> getTRelExpertOrgs() {
		return this.TRelExpertOrgs;
	}

	public void setTRelExpertOrgs(Set<TRelExpertOrg> TRelExpertOrgs) {
		this.TRelExpertOrgs = TRelExpertOrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TExpert")
	public Set<TRelExpertPaper> getTRelExpertPapers() {
		return this.TRelExpertPapers;
	}

	public void setTRelExpertPapers(Set<TRelExpertPaper> TRelExpertPapers) {
		this.TRelExpertPapers = TRelExpertPapers;
	}

}
