package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TField generated by hbm2java
 */
@Entity
@Table(name = "t_field", catalog = "db_expert_robot")
public class TField implements java.io.Serializable {

	private Integer fieldId;
	private String name;
	private String desc;
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TRelFieldTopic> TRelFieldTopics = new HashSet<TRelFieldTopic>(0);
	private Set<TRelExpertField> TRelExpertFields = new HashSet<TRelExpertField>(
			0);

	public TField() {
	}

	public TField(String name) {
		this.name = name;
	}

	public TField(String name, String desc, Set<TUser> TUsers,
			Set<TRelFieldTopic> TRelFieldTopics,
			Set<TRelExpertField> TRelExpertFields) {
		this.name = name;
		this.desc = desc;
		this.TUsers = TUsers;
		this.TRelFieldTopics = TRelFieldTopics;
		this.TRelExpertFields = TRelExpertFields;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fieldId", unique = true, nullable = false)
	public Integer getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(Integer fieldId) {
		this.fieldId = fieldId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desc", length = 65535)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TFields")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TField")
	public Set<TRelFieldTopic> getTRelFieldTopics() {
		return this.TRelFieldTopics;
	}

	public void setTRelFieldTopics(Set<TRelFieldTopic> TRelFieldTopics) {
		this.TRelFieldTopics = TRelFieldTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TField")
	public Set<TRelExpertField> getTRelExpertFields() {
		return this.TRelExpertFields;
	}

	public void setTRelExpertFields(Set<TRelExpertField> TRelExpertFields) {
		this.TRelExpertFields = TRelExpertFields;
	}

}
