package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TJournal generated by hbm2java
 */
@Entity
@Table(name = "t_journal", catalog = "db_expert_robot")
public class TJournal implements java.io.Serializable {

	private Integer jourId;
	private String name;
	private String url;
	private Set<TRelPaperJournal> TRelPaperJournals = new HashSet<TRelPaperJournal>(
			0);

	public TJournal() {
	}

	public TJournal(String name) {
		this.name = name;
	}

	public TJournal(String name, String url,
			Set<TRelPaperJournal> TRelPaperJournals) {
		this.name = name;
		this.url = url;
		this.TRelPaperJournals = TRelPaperJournals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "jourId", unique = true, nullable = false)
	public Integer getJourId() {
		return this.jourId;
	}

	public void setJourId(Integer jourId) {
		this.jourId = jourId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TJournal")
	public Set<TRelPaperJournal> getTRelPaperJournals() {
		return this.TRelPaperJournals;
	}

	public void setTRelPaperJournals(Set<TRelPaperJournal> TRelPaperJournals) {
		this.TRelPaperJournals = TRelPaperJournals;
	}

}
