package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TOrgnization generated by hbm2java
 */
@Entity
@Table(name = "t_orgnization", catalog = "db_expert_robot")
public class TOrgnization implements java.io.Serializable {

	private Integer orgId;
	private TOrgnization TOrgnization;
	private String name;
	private String address;
	private Set<TRelExpertOrg> TRelExpertOrgs = new HashSet<TRelExpertOrg>(0);
	private Set<TOrgnization> TOrgnizations = new HashSet<TOrgnization>(0);

	public TOrgnization() {
	}

	public TOrgnization(String name) {
		this.name = name;
	}

	public TOrgnization(TOrgnization TOrgnization, String name, String address,
			Set<TRelExpertOrg> TRelExpertOrgs, Set<TOrgnization> TOrgnizations) {
		this.TOrgnization = TOrgnization;
		this.name = name;
		this.address = address;
		this.TRelExpertOrgs = TRelExpertOrgs;
		this.TOrgnizations = TOrgnizations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orgId", unique = true, nullable = false)
	public Integer getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "belongsTo")
	public TOrgnization getTOrgnization() {
		return this.TOrgnization;
	}

	public void setTOrgnization(TOrgnization TOrgnization) {
		this.TOrgnization = TOrgnization;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOrgnization")
	public Set<TRelExpertOrg> getTRelExpertOrgs() {
		return this.TRelExpertOrgs;
	}

	public void setTRelExpertOrgs(Set<TRelExpertOrg> TRelExpertOrgs) {
		this.TRelExpertOrgs = TRelExpertOrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TOrgnization")
	public Set<TOrgnization> getTOrgnizations() {
		return this.TOrgnizations;
	}

	public void setTOrgnizations(Set<TOrgnization> TOrgnizations) {
		this.TOrgnizations = TOrgnizations;
	}

}
