package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TPaper generated by hbm2java
 */
@Entity
@Table(name = "t_paper", catalog = "db_expert_robot")
public class TPaper implements java.io.Serializable {

	private Integer paperId;
	private String title;
	private String abs;
	private String keywords;
	private Set<TRelPaperJournal> TRelPaperJournals = new HashSet<TRelPaperJournal>(
			0);
	private Set<TTopic> TTopics = new HashSet<TTopic>(0);
	private Set<TRelExpertPaper> TRelExpertPapers = new HashSet<TRelExpertPaper>(
			0);

	public TPaper() {
	}

	public TPaper(String title, String abs) {
		this.title = title;
		this.abs = abs;
	}

	public TPaper(String title, String abs, String keywords,
			Set<TRelPaperJournal> TRelPaperJournals, Set<TTopic> TTopics,
			Set<TRelExpertPaper> TRelExpertPapers) {
		this.title = title;
		this.abs = abs;
		this.keywords = keywords;
		this.TRelPaperJournals = TRelPaperJournals;
		this.TTopics = TTopics;
		this.TRelExpertPapers = TRelExpertPapers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "paperId", unique = true, nullable = false)
	public Integer getPaperId() {
		return this.paperId;
	}

	public void setPaperId(Integer paperId) {
		this.paperId = paperId;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "abs", nullable = false, length = 65535)
	public String getAbs() {
		return this.abs;
	}

	public void setAbs(String abs) {
		this.abs = abs;
	}

	@Column(name = "keywords", length = 65535)
	public String getKeywords() {
		return this.keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPaper")
	public Set<TRelPaperJournal> getTRelPaperJournals() {
		return this.TRelPaperJournals;
	}

	public void setTRelPaperJournals(Set<TRelPaperJournal> TRelPaperJournals) {
		this.TRelPaperJournals = TRelPaperJournals;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_rel_paper_topic", catalog = "db_expert_robot", joinColumns = { @JoinColumn(name = "paperId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "topicId", nullable = false, updatable = false) })
	public Set<TTopic> getTTopics() {
		return this.TTopics;
	}

	public void setTTopics(Set<TTopic> TTopics) {
		this.TTopics = TTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPaper")
	public Set<TRelExpertPaper> getTRelExpertPapers() {
		return this.TRelExpertPapers;
	}

	public void setTRelExpertPapers(Set<TRelExpertPaper> TRelExpertPapers) {
		this.TRelExpertPapers = TRelExpertPapers;
	}

}
