package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TPatent generated by hbm2java
 */
@Entity
@Table(name = "t_patent", catalog = "db_expert_robot")
public class TPatent implements java.io.Serializable {

	private int patentId;
	private String title;
	private String abs;
	private Date date;
	private String applicant;
	private String inventor;
	private Set<TRelExpertPatent> TRelExpertPatents = new HashSet<TRelExpertPatent>(
			0);

	public TPatent() {
	}

	public TPatent(int patentId, String title, String abs, Date date,
			String applicant, String inventor) {
		this.patentId = patentId;
		this.title = title;
		this.abs = abs;
		this.date = date;
		this.applicant = applicant;
		this.inventor = inventor;
	}

	public TPatent(int patentId, String title, String abs, Date date,
			String applicant, String inventor,
			Set<TRelExpertPatent> TRelExpertPatents) {
		this.patentId = patentId;
		this.title = title;
		this.abs = abs;
		this.date = date;
		this.applicant = applicant;
		this.inventor = inventor;
		this.TRelExpertPatents = TRelExpertPatents;
	}

	@Id
	@Column(name = "patentId", unique = true, nullable = false)
	public int getPatentId() {
		return this.patentId;
	}

	public void setPatentId(int patentId) {
		this.patentId = patentId;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "abs", nullable = false, length = 65535)
	public String getAbs() {
		return this.abs;
	}

	public void setAbs(String abs) {
		this.abs = abs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "applicant", nullable = false, length = 50)
	public String getApplicant() {
		return this.applicant;
	}

	public void setApplicant(String applicant) {
		this.applicant = applicant;
	}

	@Column(name = "inventor", nullable = false, length = 50)
	public String getInventor() {
		return this.inventor;
	}

	public void setInventor(String inventor) {
		this.inventor = inventor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TPatent")
	public Set<TRelExpertPatent> getTRelExpertPatents() {
		return this.TRelExpertPatents;
	}

	public void setTRelExpertPatents(Set<TRelExpertPatent> TRelExpertPatents) {
		this.TRelExpertPatents = TRelExpertPatents;
	}

}
