package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelExpertPaper generated by hbm2java
 */
@Entity
@Table(name = "t_rel_expert_paper", catalog = "db_expert_robot")
public class TRelExpertPaper implements java.io.Serializable {

	private TRelExpertPaperId id;
	private TExpert TExpert;
	private TPaper TPaper;
	private int authorNum;

	public TRelExpertPaper() {
	}

	public TRelExpertPaper(TRelExpertPaperId id, TExpert TExpert,
			TPaper TPaper, int authorNum) {
		this.id = id;
		this.TExpert = TExpert;
		this.TPaper = TPaper;
		this.authorNum = authorNum;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "expertId", column = @Column(name = "expertId", nullable = false)),
			@AttributeOverride(name = "paperId", column = @Column(name = "paperId", nullable = false)) })
	public TRelExpertPaperId getId() {
		return this.id;
	}

	public void setId(TRelExpertPaperId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expertId", nullable = false, insertable = false, updatable = false)
	public TExpert getTExpert() {
		return this.TExpert;
	}

	public void setTExpert(TExpert TExpert) {
		this.TExpert = TExpert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "paperId", nullable = false, insertable = false, updatable = false)
	public TPaper getTPaper() {
		return this.TPaper;
	}

	public void setTPaper(TPaper TPaper) {
		this.TPaper = TPaper;
	}

	@Column(name = "authorNum", nullable = false)
	public int getAuthorNum() {
		return this.authorNum;
	}

	public void setAuthorNum(int authorNum) {
		this.authorNum = authorNum;
	}

}
