package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TRelPaperJournalId generated by hbm2java
 */
@Embeddable
public class TRelPaperJournalId implements java.io.Serializable {

	private int paperId;
	private int jourId;

	public TRelPaperJournalId() {
	}

	public TRelPaperJournalId(int paperId, int jourId) {
		this.paperId = paperId;
		this.jourId = jourId;
	}

	@Column(name = "paperId", nullable = false)
	public int getPaperId() {
		return this.paperId;
	}

	public void setPaperId(int paperId) {
		this.paperId = paperId;
	}

	@Column(name = "jourId", nullable = false)
	public int getJourId() {
		return this.jourId;
	}

	public void setJourId(int jourId) {
		this.jourId = jourId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TRelPaperJournalId))
			return false;
		TRelPaperJournalId castOther = (TRelPaperJournalId) other;

		return (this.getPaperId() == castOther.getPaperId())
				&& (this.getJourId() == castOther.getJourId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPaperId();
		result = 37 * result + this.getJourId();
		return result;
	}

}
