package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelFieldTopic generated by hbm2java
 */
@Entity
@Table(name = "t_rel_field_topic", catalog = "db_expert_robot")
public class TRelFieldTopic implements java.io.Serializable {

	private TRelFieldTopicId id;
	private TField TField;
	private TTopic TTopic;
	private Integer relationType;

	public TRelFieldTopic() {
	}

	public TRelFieldTopic(TRelFieldTopicId id, TField TField, TTopic TTopic) {
		this.id = id;
		this.TField = TField;
		this.TTopic = TTopic;
	}

	public TRelFieldTopic(TRelFieldTopicId id, TField TField, TTopic TTopic,
			Integer relationType) {
		this.id = id;
		this.TField = TField;
		this.TTopic = TTopic;
		this.relationType = relationType;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fieldId", column = @Column(name = "fieldId", nullable = false)),
			@AttributeOverride(name = "topicId", column = @Column(name = "topicId", nullable = false)) })
	public TRelFieldTopicId getId() {
		return this.id;
	}

	public void setId(TRelFieldTopicId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fieldId", nullable = false, insertable = false, updatable = false)
	public TField getTField() {
		return this.TField;
	}

	public void setTField(TField TField) {
		this.TField = TField;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topicId", nullable = false, insertable = false, updatable = false)
	public TTopic getTTopic() {
		return this.TTopic;
	}

	public void setTTopic(TTopic TTopic) {
		this.TTopic = TTopic;
	}

	@Column(name = "relationType")
	public Integer getRelationType() {
		return this.relationType;
	}

	public void setRelationType(Integer relationType) {
		this.relationType = relationType;
	}

}
