package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelExpertField generated by hbm2java
 */
@Entity
@Table(name = "t_rel_expert_field", catalog = "db_expert_robot")
public class TRelExpertField implements java.io.Serializable {

	private TRelExpertFieldId id;
	private TExpert TExpert;
	private TField TField;
	private Integer weight;

	public TRelExpertField() {
	}

	public TRelExpertField(TRelExpertFieldId id, TExpert TExpert, TField TField) {
		this.id = id;
		this.TExpert = TExpert;
		this.TField = TField;
	}

	public TRelExpertField(TRelExpertFieldId id, TExpert TExpert,
			TField TField, Integer weight) {
		this.id = id;
		this.TExpert = TExpert;
		this.TField = TField;
		this.weight = weight;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "expertId", column = @Column(name = "expertId", nullable = false)),
			@AttributeOverride(name = "fieldId", column = @Column(name = "fieldId", nullable = false)) })
	public TRelExpertFieldId getId() {
		return this.id;
	}

	public void setId(TRelExpertFieldId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expertId", nullable = false, insertable = false, updatable = false)
	public TExpert getTExpert() {
		return this.TExpert;
	}

	public void setTExpert(TExpert TExpert) {
		this.TExpert = TExpert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fieldId", nullable = false, insertable = false, updatable = false)
	public TField getTField() {
		return this.TField;
	}

	public void setTField(TField TField) {
		this.TField = TField;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

}
