package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TRelExpertFieldId generated by hbm2java
 */
@Embeddable
public class TRelExpertFieldId implements java.io.Serializable {

	private int expertId;
	private int fieldId;

	public TRelExpertFieldId() {
	}

	public TRelExpertFieldId(int expertId, int fieldId) {
		this.expertId = expertId;
		this.fieldId = fieldId;
	}

	@Column(name = "expertId", nullable = false)
	public int getExpertId() {
		return this.expertId;
	}

	public void setExpertId(int expertId) {
		this.expertId = expertId;
	}

	@Column(name = "fieldId", nullable = false)
	public int getFieldId() {
		return this.fieldId;
	}

	public void setFieldId(int fieldId) {
		this.fieldId = fieldId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TRelExpertFieldId))
			return false;
		TRelExpertFieldId castOther = (TRelExpertFieldId) other;

		return (this.getExpertId() == castOther.getExpertId())
				&& (this.getFieldId() == castOther.getFieldId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExpertId();
		result = 37 * result + this.getFieldId();
		return result;
	}

}
