package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelExpertTopic generated by hbm2java
 */
@Entity
@Table(name = "t_rel_expert_topic", catalog = "db_expert_robot")
public class TRelExpertTopic implements java.io.Serializable {

	private TRelExpertTopicId id;
	private TExpert TExpert;
	private TTopic TTopic;
	private Integer weight;

	public TRelExpertTopic() {
	}

	public TRelExpertTopic(TRelExpertTopicId id, TExpert TExpert, TTopic TTopic) {
		this.id = id;
		this.TExpert = TExpert;
		this.TTopic = TTopic;
	}

	public TRelExpertTopic(TRelExpertTopicId id, TExpert TExpert,
			TTopic TTopic, Integer weight) {
		this.id = id;
		this.TExpert = TExpert;
		this.TTopic = TTopic;
		this.weight = weight;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "expertId", column = @Column(name = "expertId", nullable = false)),
			@AttributeOverride(name = "topicId", column = @Column(name = "topicId", nullable = false)) })
	public TRelExpertTopicId getId() {
		return this.id;
	}

	public void setId(TRelExpertTopicId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expertId", nullable = false, insertable = false, updatable = false)
	public TExpert getTExpert() {
		return this.TExpert;
	}

	public void setTExpert(TExpert TExpert) {
		this.TExpert = TExpert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "topicId", nullable = false, insertable = false, updatable = false)
	public TTopic getTTopic() {
		return this.TTopic;
	}

	public void setTTopic(TTopic TTopic) {
		this.TTopic = TTopic;
	}

	@Column(name = "weight")
	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

}
