package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelExpertOrg generated by hbm2java
 */
@Entity
@Table(name = "t_rel_expert_org", catalog = "db_expert_robot")
public class TRelExpertOrg implements java.io.Serializable {

	private TRelExpertOrgId id;
	private TExpert TExpert;
	private TOrgnization TOrgnization;
	private String job;

	public TRelExpertOrg() {
	}

	public TRelExpertOrg(TRelExpertOrgId id, TExpert TExpert,
			TOrgnization TOrgnization) {
		this.id = id;
		this.TExpert = TExpert;
		this.TOrgnization = TOrgnization;
	}

	public TRelExpertOrg(TRelExpertOrgId id, TExpert TExpert,
			TOrgnization TOrgnization, String job) {
		this.id = id;
		this.TExpert = TExpert;
		this.TOrgnization = TOrgnization;
		this.job = job;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "expertId", column = @Column(name = "expertId", nullable = false)),
			@AttributeOverride(name = "orgId", column = @Column(name = "orgId", nullable = false)) })
	public TRelExpertOrgId getId() {
		return this.id;
	}

	public void setId(TRelExpertOrgId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expertId", nullable = false, insertable = false, updatable = false)
	public TExpert getTExpert() {
		return this.TExpert;
	}

	public void setTExpert(TExpert TExpert) {
		this.TExpert = TExpert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orgId", nullable = false, insertable = false, updatable = false)
	public TOrgnization getTOrgnization() {
		return this.TOrgnization;
	}

	public void setTOrgnization(TOrgnization TOrgnization) {
		this.TOrgnization = TOrgnization;
	}

	@Column(name = "job", length = 20)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

}
