package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TRelExpertPatent generated by hbm2java
 */
@Entity
@Table(name = "t_rel_expert_patent", catalog = "db_expert_robot")
public class TRelExpertPatent implements java.io.Serializable {

	private TRelExpertPatentId id;
	private TExpert TExpert;
	private TPatent TPatent;
	private int authorOrder;

	public TRelExpertPatent() {
	}

	public TRelExpertPatent(TRelExpertPatentId id, TExpert TExpert,
			TPatent TPatent, int authorOrder) {
		this.id = id;
		this.TExpert = TExpert;
		this.TPatent = TPatent;
		this.authorOrder = authorOrder;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "expertId", column = @Column(name = "expertId", nullable = false)),
			@AttributeOverride(name = "patentId", column = @Column(name = "patentId", nullable = false)) })
	public TRelExpertPatentId getId() {
		return this.id;
	}

	public void setId(TRelExpertPatentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expertId", nullable = false, insertable = false, updatable = false)
	public TExpert getTExpert() {
		return this.TExpert;
	}

	public void setTExpert(TExpert TExpert) {
		this.TExpert = TExpert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "patentId", nullable = false, insertable = false, updatable = false)
	public TPatent getTPatent() {
		return this.TPatent;
	}

	public void setTPatent(TPatent TPatent) {
		this.TPatent = TPatent;
	}

	@Column(name = "authorOrder", nullable = false)
	public int getAuthorOrder() {
		return this.authorOrder;
	}

	public void setAuthorOrder(int authorOrder) {
		this.authorOrder = authorOrder;
	}

}
