package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TRelExpertOrgId generated by hbm2java
 */
@Embeddable
public class TRelExpertOrgId implements java.io.Serializable {

	private int expertId;
	private int orgId;

	public TRelExpertOrgId() {
	}

	public TRelExpertOrgId(int expertId, int orgId) {
		this.expertId = expertId;
		this.orgId = orgId;
	}

	@Column(name = "expertId", nullable = false)
	public int getExpertId() {
		return this.expertId;
	}

	public void setExpertId(int expertId) {
		this.expertId = expertId;
	}

	@Column(name = "orgId", nullable = false)
	public int getOrgId() {
		return this.orgId;
	}

	public void setOrgId(int orgId) {
		this.orgId = orgId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TRelExpertOrgId))
			return false;
		TRelExpertOrgId castOther = (TRelExpertOrgId) other;

		return (this.getExpertId() == castOther.getExpertId())
				&& (this.getOrgId() == castOther.getOrgId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getExpertId();
		result = 37 * result + this.getOrgId();
		return result;
	}

}
