package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TTopic generated by hbm2java
 */
@Entity
@Table(name = "t_topic", catalog = "db_expert_robot")
public class TTopic implements java.io.Serializable {

	private Integer topicId;
	private String name;
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TRelExpertTopic> TRelExpertTopics = new HashSet<TRelExpertTopic>(
			0);
	private Set<TPaper> TPapers = new HashSet<TPaper>(0);
	private Set<TRelFieldTopic> TRelFieldTopics = new HashSet<TRelFieldTopic>(0);

	public TTopic() {
	}

	public TTopic(String name) {
		this.name = name;
	}

	public TTopic(String name, Set<TUser> TUsers,
			Set<TRelExpertTopic> TRelExpertTopics, Set<TPaper> TPapers,
			Set<TRelFieldTopic> TRelFieldTopics) {
		this.name = name;
		this.TUsers = TUsers;
		this.TRelExpertTopics = TRelExpertTopics;
		this.TPapers = TPapers;
		this.TRelFieldTopics = TRelFieldTopics;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "topicId", unique = true, nullable = false)
	public Integer getTopicId() {
		return this.topicId;
	}

	public void setTopicId(Integer topicId) {
		this.topicId = topicId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TTopics")
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTopic")
	public Set<TRelExpertTopic> getTRelExpertTopics() {
		return this.TRelExpertTopics;
	}

	public void setTRelExpertTopics(Set<TRelExpertTopic> TRelExpertTopics) {
		this.TRelExpertTopics = TRelExpertTopics;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "TTopics")
	public Set<TPaper> getTPapers() {
		return this.TPapers;
	}

	public void setTPapers(Set<TPaper> TPapers) {
		this.TPapers = TPapers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TTopic")
	public Set<TRelFieldTopic> getTRelFieldTopics() {
		return this.TRelFieldTopics;
	}

	public void setTRelFieldTopics(Set<TRelFieldTopic> TRelFieldTopics) {
		this.TRelFieldTopics = TRelFieldTopics;
	}

}
