package com.robot.model;

// Generated 2015-5-10 13:38:59 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_user", catalog = "db_expert_robot")
public class TUser implements java.io.Serializable {

	private String userId;
	private String password;
	private String nickname;
	private boolean auth;
	private Set<TExpert> TExperts = new HashSet<TExpert>(0);
	private Set<TField> TFields = new HashSet<TField>(0);
	private Set<TTopic> TTopics = new HashSet<TTopic>(0);

	public TUser() {
	}

	public TUser(String userId, String password, String nickname, boolean auth) {
		this.userId = userId;
		this.password = password;
		this.nickname = nickname;
		this.auth = auth;
	}

	public TUser(String userId, String password, String nickname, boolean auth,
			Set<TExpert> TExperts, Set<TField> TFields, Set<TTopic> TTopics) {
		this.userId = userId;
		this.password = password;
		this.nickname = nickname;
		this.auth = auth;
		this.TExperts = TExperts;
		this.TFields = TFields;
		this.TTopics = TTopics;
	}

	@Id
	@Column(name = "userId", unique = true, nullable = false, length = 10)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nickname", nullable = false, length = 20)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "auth", nullable = false)
	public boolean isAuth() {
		return this.auth;
	}

	public void setAuth(boolean auth) {
		this.auth = auth;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_follow_user_expert", catalog = "db_expert_robot", joinColumns = { @JoinColumn(name = "userId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "expertId", nullable = false, updatable = false) })
	public Set<TExpert> getTExperts() {
		return this.TExperts;
	}

	public void setTExperts(Set<TExpert> TExperts) {
		this.TExperts = TExperts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_follow_user_field", catalog = "db_expert_robot", joinColumns = { @JoinColumn(name = "userId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "fieldId", nullable = false, updatable = false) })
	public Set<TField> getTFields() {
		return this.TFields;
	}

	public void setTFields(Set<TField> TFields) {
		this.TFields = TFields;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_follow_user_topic", catalog = "db_expert_robot", joinColumns = { @JoinColumn(name = "userId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "topicId", nullable = false, updatable = false) })
	public Set<TTopic> getTTopics() {
		return this.TTopics;
	}

	public void setTTopics(Set<TTopic> TTopics) {
		this.TTopics = TTopics;
	}

}
